/*******************************************************************\
* File Name:   Bounce.H                                             *
*                                                                   *
* Description: Header file for Bounce.RC.                           *
*                                                                   *
*              This file contains the constants used by Bounce.RC.  *
*              These lines have been removed from Bounce.RC to      *
*              clean up the code of the script file.                *
*              The constants have been extracted from the PMWIN.H   *
*              header file to reduce resource file size.            *
\*******************************************************************/
#define VK_SPACE            0x10
#define VK_SCRLLOCK         0x1C
#define VK_ESC              0x0F
#define SS_BKGNDRECT        0x0007L
#define SS_FGNDFRAME        0x0008L
#define WC_STATIC           0xffff0005L
#define WC_SCROLLBAR        0xffff0008L
#define WS_GROUP            0x00010000L
#define WS_SAVEBITS         0x04000000L
#define WS_CLIPSIBLINGS     0x10000000L
#define WS_VISIBLE          0x80000000L
#define SBS_HORZ            0L
#define SBS_VERT            1L
#define ID_MENU             1
#define ID_ACCEL            1
#define IDM_CONTROL         2
#define IDM_OPTIONS         3
#define IDM_C_START         4
#define IDM_C_STOP          5
#define IDM_C_PAUSE         6
#define IDM_C_CONT          7
#define IDM_C_EXIT          8
#define IDM_O_SOUND         9
#define IDM_O_SIZE          10
#define IDM_O_VELOCITY      11
#define IDM_O_POS           12
#define IDM_O_TRAIL         13
#define IDM_O_ANGLE         14
#define IDM_O_S_RAND        16
#define IDM_O_S_SCROLL      17
#define IDM_O_S_CURRENT     18
#define IDM_O_S_OK          19
#define IDM_O_V_SCROLL      21
#define IDM_O_V_CURRENT     22
#define IDM_O_V_OK          23
#define IDM_O_P_VSCROLL     25
#define IDM_O_P_HSCROLL     26
#define IDM_O_P_X           28
#define IDM_O_P_Y           29
#define IDM_O_P_OK          30
#define IDM_O_A_SCROLL      32
#define IDM_O_A_CURRENT     33
#define IDM_O_A_OK          34
